### PR TITLE
add new k80 flavors to GPU tier

### PR DESCRIPTION
**Pull request by jtriley**
These hypervisors were recently added during 20230918 maintenance.

### CODE REVIEW

**Review by Milstein — APPROVED** [review]
Looks good to me as per out new flavor docs.

**Review by joachimweyl — APPROVED** [review]

**Review by Milstein — CHANGES_REQUESTED** [review]
We decided to remove `gpu-su-v100.1m` and update the `gpu-su-v100.1` definition as per our new flavor definition

**Comment by jtriley** [comment]
> We decided to remove `gpu-su-v100.1m` and update the `gpu-su-v100.1` definition as per our new flavor definition doc and also need to update the flavors.yml

Sounds good - we should be able to merge this first and then update those details in a separate PR.

**Review by Milstein — APPROVED** [review]
LGTM based on our new flavor definition excel docs file.

**Pull request merged**
